version: "3.8"

services:
  app:
    container_name: rowerex-front
    image: rowerex-front:dev-latest
    build:
      context: .
      target: development
    volumes:
      - .:/app
    ports:
      - 3000:3000
