version: "3.8"

services:
  rowerex-frontend:
    container_name: rowerex-front
    build:
      context: .
      target: development
    volumes:
      - .:/app
    ports:
      - 3000:3000
    environment:
      REACT_APP_BACKENDURL: http://api.velog.local/api

  proxy:
    depends_on:
      - rowerex-php
      - rowerex-frontend
    image: ghcr.io/rowerex/promxy:latest
    ports:
      - '80:80'
    restart: "unless-stopped"
    environment:
      FRONT_URL: app.velog.local
      FRONT_PORT: 3000
      API_URL: api.velog.local
      PHP_PORT: 9000

  rowerex-php:
    image: ghcr.io/rowerex/rowerex:latest
    environment:
      SERVER_NAME: api.velog.local

  rowerex-database:
    container_name: rowerex-database
    platform: linux/x86_64
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "${ROWEREX_DB_PASSWORD:-secret}"
      MYSQL_DATABASE: rowerex
      MYSQL_USER: rowerex
      MYSQL_PASSWORD: rowerex
    ports:
      - '33306:3306'
    volumes:
      - ~/databases/rowerex:/var/lib/mysql
    restart: "unless-stopped"