version: "3.8"

services:
  app:
    container_name: rowerex-front
    image: rowerex-front
    build:
      context: .
      target: development
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000
  app-prod:
    container_name: rowerex-front-prod
    image: rowerex-front
    build:
      context: .
      target: prod
    ports:
      - "8889:80"
