version: "3.8"

services:
  app:
    container_name: rowerex-front
    build:
      context: .
      target: development
    volumes:
      - .:/app
    ports:
      - 3000:3000
    environment:
      REACT_APP_BACKENDURL: http://api.velog.local:8080/api