name: Pipeline
on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build development image
        run: >
          docker buildx build
          --cache-from=ghcr.io/rowerex/frontend:latest
          --target development --tag ghcr.io/rowerex/frontend:development .
      -
        name: Run linter
        run: docker run --rm ghcr.io/rowerex/frontend:development npx eslint --no-ignore .
      -
        name: Build production image
        # temporary workaround until eslint errors are fixed
        if: success() || failure()
        run: >
          docker buildx build
          --cache-from=ghcr.io/rowerex/frontend:latest
          --cache-to=type=inline
          --target prod --tag ghcr.io/rowerex/frontend:latest .
      -
        name: Push to registry
        run: docker push ghcr.io/rowerex/frontend:latest
      - 
        name: Push tag to registry
        run: >
          if [ $(git tag --points-at) ] ; then
            export TAG=$(git tag --points-at)
            export IMAGE=ghcr.io/rowerex/frontend
            docker tag $IMAGE:latest $IMAGE:$TAG
            docker push $IMAGE:$TAG
          else
            echo "No git tag at current commit - do nothing"
          fi
